// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AuthCallback() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"mx-auto flex min-h-[60vh] max-w-md flex-col items-center justify-center gap-4 text-center\"><div class=\"h-10 w-10 animate-spin rounded-full border-4 border-gray-300 border-t-indigo-600\"></div><h1 class=\"text-2xl font-semibold text-gray-800\">Finishing sign-in</h1><p id=\"auth-callback-status\" class=\"text-sm text-gray-600\">Waiting for your session to be available...</p></div><script>\r\n\t\t(async function waitForSession() {\r\n\t\t\tconst statusEl = document.getElementById('auth-callback-status');\r\n\t\t\tconst maxAttempts = 20;\r\n\r\n\t\t\tfor (let attempt = 0; attempt < maxAttempts; attempt++) {\r\n\t\t\t\ttry {\r\n\t\t\t\t\tconst response = await fetch('/auth/status', {\r\n\t\t\t\t\t\tcredentials: 'same-origin',\r\n\t\t\t\t\t\tcache: 'no-store',\r\n\t\t\t\t\t});\r\n\r\n\t\t\t\t\tif (response.ok) {\r\n\t\t\t\t\t\twindow.location.replace('/dashboard');\r\n\t\t\t\t\t\treturn;\r\n\t\t\t\t\t}\r\n\t\t\t\t} catch (error) {\r\n\t\t\t\t\tconsole.warn('Auth status check failed:', error);\r\n\t\t\t\t}\r\n\r\n\t\t\t\tif (statusEl) {\r\n\t\t\t\t\tstatusEl.textContent = 'Waiting for your session to be available... (' + (attempt + 1) + '/' + maxAttempts + ')';\r\n\t\t\t\t}\r\n\r\n\t\t\t\tawait new Promise((resolve) => setTimeout(resolve, 250));\r\n\t\t\t}\r\n\r\n\t\t\twindow.location.replace('/sign-in');\r\n\t\t})();\r\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
