// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"baselix/internal/views/components"
)

func Dashboard(userID string, sessionID string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-4xl mx-auto\"><h1 class=\"text-3xl font-bold text-gray-800 mb-2\">Dashboard</h1><p class=\"text-gray-500 mb-8\">Welcome back! Here's an overview.</p><div class=\"grid grid-cols-1 sm:grid-cols-3 gap-6\"><div class=\"bg-white rounded-xl shadow p-6\"><p class=\"text-sm text-gray-500 uppercase tracking-wide\">Users</p><p class=\"text-3xl font-bold text-indigo-600 mt-1\">0</p></div><div class=\"bg-white rounded-xl shadow p-6\"><p class=\"text-sm text-gray-500 uppercase tracking-wide\">Sessions</p><p class=\"text-3xl font-bold text-indigo-600 mt-1\">0</p></div><div class=\"bg-white rounded-xl shadow p-6\"><p class=\"text-sm text-gray-500 uppercase tracking-wide\">Requests</p><p class=\"text-3xl font-bold text-indigo-600 mt-1\">0</p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.ProjectForm().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"mt-8\"><h2 class=\"text-2xl font-bold text-gray-800 mb-4\">Your Projects</h2><p class=\"text-gray-500 mb-6\">Manage your projects and API keys.</p><div id=\"project-list\" class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\" hx-get=\"/projects\" hx-trigger=\"load, projects-updated from:body\" hx-target=\"#project-list\" hx-swap=\"innerHTML\"><!-- Project cards will go here --></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
