// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Nav() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"bg-gray-900 shadow-md\"><div class=\"container mx-auto px-4 py-3 flex items-center justify-between\"><!-- Logo + Name as single home link --><a href=\"/\" class=\"flex items-center space-x-2\"><img src=\"/static/media/logo.ico\" alt=\"Baselix Logo\" class=\"h-8 w-8\"> <span class=\"text-white text-xl font-bold tracking-wide\">Baselix</span></a><!-- Navigation links --><ul class=\"flex items-center space-x-6\"><li><a href=\"/\" class=\"text-gray-300 hover:text-white transition-colors\">Home</a></li><li><a href=\"/dashboard\" class=\"text-gray-300 hover:text-white transition-colors\">Dashboard</a></li><!-- Clerk Auth Area --><li id=\"clerk-auth-area\" class=\"flex items-center justify-center min-w-[100px] h-9\" style=\"visibility:hidden;\"><a id=\"clerk-sign-in-link\" href=\"/sign-in\" class=\"flex items-center bg-indigo-600 hover:bg-indigo-700 text-white px-4 rounded-lg text-sm font-semibold transition-colors h-9\">Sign In</a><div id=\"clerk-user-button\" class=\"flex items-center justify-center h-9\" style=\"display:none;\"></div></li></ul></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
